export default {
	"app-name": "圈乎",
	"activity": "活动",
	"activity-new": " 发布活动",
	"activity-current": "当前活动",
	"activity-past": "往期活动",
	"activity-view-detail": "查看活动详情",
	'cancel-activity': '取消活动',
	"activity-time": "活动时间",
	"activity-address": "活动地址",
	'no-find-addr': '没有找到对应位置',
	"activity-intro": "活动简介",
	"activity-prizes": "活动奖品",
	"navigation": "导航",
	"activity-detail": "活动详情",
	"before-start": "未开始",
	"signup": "报名中",
	"ongoing": "进行中",
	"ended": "已结束",
	"to": "至",
	"p": "请",
	"num": "号",
	"fill": "填写",
	"upload-fm-img": "上传封面图",
	"change-fm-img": "更改封面图",
	'publish-activity-name': '请填写活动名称',
	"activity-home": "活动主页",
	"activity-start-time": "距离活动开始还有",
	"activity-end-time": "距离活动结束还有",
	"day": "天",
	"hours": "时",
	"minutes": "分",
	"seconds": "秒",
	"start-time": "活动开始时间",
	"end-time": "活动结束时间",

	"share-to": "分享到",
	"share-YRIM": "聊天",
	"share-YRShow": "悠友圈",
	"share-WeChat": "微信好友",
	"share-WeChatLine": "朋友圈",
	"share-QQ": "QQ好友",
	"share-QQZone": "QQ空间",
	"share-Sina": "新浪微博",

	"loading": "正在加载...",
	"no-more-content": "没有更多啦",
	"no-comment": "暂无评论~",
	"comment-input-placeholder": "回复评论",

	"dialog-ok": "确定",
	"dialog-cancel": "取消"
}
